import 'package:flutter/material.dart';

const String DEFAULT_ICON = "computer";

final Map<String, IconData> iconDefinitions = {
  "computer": Icons.computer,
  "business": Icons.business,
  "work": Icons.business_center,
  "job": Icons.work,
  "shop": Icons.store,
  "power": Icons.power,
  "desktop": Icons.desktop_windows,
  "mac": Icons.desktop_mac,
  "laptop": Icons.laptop,
  "chromebook": Icons.laptop_chromebook,
  "macbook": Icons.laptop_mac,
  "music": Icons.music_note,
  "camera": Icons.camera_alt,
  "casino": Icons.casino,
  "cloud": Icons.cloud,
  "hardware": Icons.developer_board,
  "hub": Icons.device_hub,
  "dns": Icons.dns,
  "dvr": Icons.dvr,
  "flag": Icons.flag,
  "group": Icons.group_work,
  "headset": Icons.headset,
  "flashlight": Icons.highlight,
  "home": Icons.home,
  "homeoffice": Icons.home_work,
  "input": Icons.input,
  "kitchen": Icons.kitchen,
  "world": Icons.language,
  "layers": Icons.layers,
  "lightbulb": Icons.lightbulb_outline,
  "movie": Icons.movie,
  "printer": Icons.print,
  "city": Icons.location_city,
  "memory": Icons.memory,
  "storage": Icons.storage,
  "nature": Icons.nature,
  "nfc": Icons.nfc,
  "router": Icons.router,
  "radio": Icons.scanner,
  "sd_card": Icons.sd_card,
  "security": Icons.security,
  "speaker": Icons.speaker,
  "switch": Icons.swap_calls,
  "toy": Icons.toys,
  "tv": Icons.tv,
  "usb": Icons.usb,
  "watch": Icons.watch,
  "couch": Icons.weekend,
  "widget": Icons.widgets,
  "wifi": Icons.wifi,
};
